### ISSUE TITLE
add explanation on how to run and how to add more tests

### ISSUE THREAD

**Issue by ninrod** [noctuid/targets.el#15]
Hi!

I'd like to add more tests to the package. I never wrote an elisp test in my life, so I wonder what's going on and how the test infrastructure works. I think that buttercup is the test framework from reading the source code, but's that's all I know. 

Is Cask being used because of the test infra? 

If I run `make test` will make execute emacs in batch mode to run the tests?

**Comment by noctuid** [comment]
Yes, cask is used for tests. You can run `make cask` and then `make test` to run the tests.

If you want to add more tests, bound behavior for seeking is currently untested. You could start with something like this at the end of `test-targets.el`:
```elisp
;;; * Bound Tests
(describe "targets-bound overriden to return the boundaries of the current line"
  (before-all (defun targets-line-bound (&optional backwards)
                (if backwards
                    (line-beginning-position)
                  (line-end-position)))
              (advice-add 'targets-bound :override #'targets-line-bound))
  (after-all (advice-remove 'targets-bound #'targets-line-bound))
  (it "should let pair text objects seek within the current line"
    tests...)
  (it "should prevent pair text objects from seeking past the current line"
    tests...)
  (it "should prevent quote text objects from seeking past the current line")
  ...)
```

Pairs probably behave as expected, but I haven't really tested bounds with anything else at all, so you may find some bugs (I know for quotes it will wrongly seek forward with those changes).

If you want to add tests for something else let me know (because I may have already started working on it).

**Comment by ninrod** [comment]
Funny. `make cask` is not working for me.

```sh
targets.el ❯ make cask
/bin/sh: cask: command not found
make: Nothing to be done for `cask'.
targets.el ❯
```

**Comment by noctuid** [comment]
Do you have cask installed?

**Comment by ninrod** [comment]
Jesus I thought cask was like a lisp package, but I have to actually to install the binary. Please forgive my everlasting noobness @noctuid.
