### ISSUE TITLE
Migration from evil-textobj-anyblock

### ISSUE THREAD

**Issue by blaenk** [noctuid/targets.el#20]
I noticed the deprecation notice on evil-textobj-anyblock and thought it might be nice if the readme for this or that package included a quick section on how to replicate that behavior (the `b` object) using this package, since at least for me it wasn't immediately obvious.

The readme for this package is very in-depth and comprehensive and I got the impression that it's more do-it-yourself, i.e. that `b` doesn't come out of the box, but that one would have to create it themselves. If that's the case, code showing how to accomplish that would be nice.

**Comment by ninrod** [comment]
I don't think there's a way to replicate the `b` in evil-text-object-any-block in targets.el. targets.el is about easily adding more text objects that implement seeking out of the box.

**Comment by noctuid** [comment]
Composite text objects are just a generalization of the anyblock text object (though the functionality still needs more work/testing). I can add an example replicating the anyblock text object to the readme at some point.

**Comment by blaenk** [comment]
Yeah I think others besides myself might appreciate one. Otherwise it's pretty confusing how the existence of this repository results in the deprecation of the other.

Until such time, it may be possible for prospective users of evil-textobj-anyblock to come upon the deprecation notice, and despite the assurance to continue to use it, most users, especially new ones, tend to avoid deprecated things, favoring using the "replacement" from the get-go. So they may come to this repository but not find it immediately obvious how to replicate the functionality that attracted them to evil-textobj-anyblock to begin with, and so may give up on both.

Perhaps that's unlikely, but I think the possibility exists during this limbo period.

**Comment by noctuid** [comment]
I think the documentation for `targets-define-to` and `targets-define-composite-to` is already sufficient (let me know if you think there should be any changes) but agree that it should be more immediately obvious how to replicate the anyblock text objects without looking at any documentation. 

I've added an example. Note that the smart quotes will not currently work since targets doesn't yet work with quote text objects that have different start and end characters (bug). There are also some seeking cases where it fails. Please let me know if you try this and find any other issues.
