### ISSUE TITLE
Unable to replicate evil-textobj-anyblock with doc code.

### ISSUE THREAD

**Issue by larebsyed** [noctuid/targets.el#28]
``(targets-define-composite-to anyblock
  (("(" ")" pair)
   ("[" "]" pair)
   ("{" "}" pair)
   ("<" ">" pair)
   ("\"" "\"" quote)
   ("'" "'" quote)
   ("`" "`" quote)
   ("“" "”" quote))
  :bind t
  :keys "b")``

Error Message: No evil-qoute here

**Comment by noctuid** [comment]
I'm not sure exactly how you are using it, but I imagine the issue is that there needs to be an `ignore-errors` somewhere to prevent errors from stopping execution when there are no quotes. I probably will not attempt to fix this issue here because I've completely rewritten the code for handling of composite text objects. I am still working on the functionality provide by targets.el but in a different repository. Unfortunately, it is not ready to be used, but you can follow the repository for updates if you want: https://github.com/noctuid/things.el

**Comment by larebsyed** [comment]
@noctuid Is things.el a replacement for targets.el?

**Comment by noctuid** [comment]
things-evil.el will replace targets.el (or I may keep the name "targets"; I haven't decided). At the moment, it is fairly unstable and does not implement all of targets' functionality.
