### ISSUE TITLE
We could provide a function argument text object

### ISSUE THREAD

**Issue by ninrod** [noctuid/targets.el#3]
for example: 

```js
//cursor in [c]
// command: daa
var a = func(a,b,[c]);

// result:
var a = func(a,b)
```

What do you think?

I'm actually willing to implement it to learn some proper elisp.

**Comment by noctuid** [comment]
Since [evil-args](https://github.com/wcsmith/evil-args) exists, this is low priority for me. I can look into implementing it after I'm done with the basics. It actually may not require any elisp to implement (just a regex with a pair text object). I can test to see if that works okay when I get a chance.

**Comment by ninrod** [comment]
@noctuid, you are absolutelly right. evil-args works nicely already so focus should be spent on core targets functionality.
